#!/usr/bin/env bash
# xgm-egpu test-suite. No root, no hardware, no network: every check runs the
# tool's functions in library mode against fixture files in a temp dir.
#
#   tests/run.sh
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
PASS=0; FAIL=0

pass() { PASS=$((PASS+1)); printf '  ok   %s\n' "$1"; }
fail() { FAIL=$((FAIL+1)); printf '  FAIL %s\n       %s\n' "$1" "$2"; }
assert_eq() { [[ "$2" == "$3" ]] && pass "$1" || fail "$1" "expected [$3] got [$2]"; }
assert_rc() { local label=$1 want=$2; shift 2; "$@" >/dev/null 2>&1; local rc=$?; [[ $rc -eq $want ]] && pass "$label" || fail "$label" "expected rc=$want got rc=$rc"; }
assert_has() { grep -qE -- "$3" <<<"$2" && pass "$1" || fail "$1" "missing /$3/ in: $2"; }
assert_not() { grep -qE -- "$3" <<<"$2" && fail "$1" "unexpected /$3/ in: $2" || pass "$1"; }

# Load the tool with every path pointed into the fixture tree.
load() {
    export XGM_NV_PARAMS=$T/params XGM_NV_GPUS_DIR=$T/gpus \
           XGM_MKINITCPIO_CONF=$T/mkinitcpio.conf XGM_MKINITCPIO_D=$T/mkinitcpio.conf.d \
           XGM_DISTRO_MODPROBE=$T/usrlib/nvidia.conf XGM_ETC_MODPROBE_D=$T/etc \
           XGM_AUTOPROBE=$T/drivers_autoprobe XGM_STATE_DIR=$T/state
    mkdir -p "$T/gpus" "$T/mkinitcpio.conf.d" "$T/usrlib" "$T/etc"
    # shellcheck disable=SC1091
    XGM_LIBRARY_MODE=1 source bin/xgm-egpu
}
load

echo "== nvidia_dpm_value =="
printf 'Foo: 1\nDynamicPowerManagement: 2\nDynamicPowerManagementVideoMemoryThreshold: 200\n' > "$T/params"
assert_eq "reads the module value"            "$(nvidia_dpm_value)" "2"
printf 'DynamicPowerManagement: 0\n' > "$T/params"
assert_eq "reads 0"                           "$(nvidia_dpm_value)" "0"
printf 'DynamicPowerManagementVideoMemoryThreshold: 200\n' > "$T/params"
assert_eq "does not match the Threshold key"  "$(nvidia_dpm_value)" ""
rm -f "$T/params"
assert_eq "empty when driver not loaded"      "$(nvidia_dpm_value)" ""

echo "== preflight_rtd3 =="
printf 'DynamicPowerManagement: 2\n' > "$T/params"
assert_rc "refuses when RTD3 armed (2)"       1 preflight_rtd3
printf 'DynamicPowerManagement: 3\n' > "$T/params"
assert_rc "refuses on driver default (3)"     1 preflight_rtd3
printf 'DynamicPowerManagement: 0\n' > "$T/params"
assert_rc "passes when disarmed (0)"          0 preflight_rtd3
rm -f "$T/params"
assert_rc "defers (passes) when not loaded"   0 preflight_rtd3
printf 'DynamicPowerManagement: 2\n' > "$T/params"
out=$(preflight_rtd3 2>&1)
assert_has "refusal explains the 10s timer"   "$out" "10s"
assert_has "refusal names the fix"            "$out" "install-rules"

echo "== initramfs_has_nvidia =="
printf 'MODULES=()\nHOOKS=(base)\n' > "$T/mkinitcpio.conf"
assert_rc "MODULES=() and no drop-in -> no"   1 initramfs_has_nvidia
printf 'MODULES=(nvidia nvidia_drm)\n' > "$T/mkinitcpio.conf"
assert_rc "MODULES=(nvidia) in main -> yes"   0 initramfs_has_nvidia
printf 'MODULES=()\n' > "$T/mkinitcpio.conf"
printf '# generated by chwd\nMODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)\n' > "$T/mkinitcpio.conf.d/10-chwd.conf"
assert_rc "MODULES+= in conf.d (CachyOS chwd) -> yes" 0 initramfs_has_nvidia
printf '# MODULES+=(nvidia)\n' > "$T/mkinitcpio.conf.d/10-chwd.conf"
assert_rc "commented-out drop-in -> no"       1 initramfs_has_nvidia
printf 'MODULES+=(amdgpu)\n' > "$T/mkinitcpio.conf.d/10-chwd.conf"
assert_rc "other module in drop-in -> no"     1 initramfs_has_nvidia
rm -f "$T/mkinitcpio.conf.d/10-chwd.conf"

echo "== write_modprobe_shadow =="
cat > "$T/usrlib/nvidia.conf" <<'D'
# distro file, CachyOS style, with a continuation line
options nvidia NVreg_InitializeSystemMemoryAllocations=0 \
    NVreg_DynamicPowerManagement=0x02
D
out=$(write_modprobe_shadow "$T/etc/nvidia.conf")
optline=$(grep -E '^options nvidia' <<<"$out")
assert_has "keeps the distro's other option"  "$optline" "NVreg_InitializeSystemMemoryAllocations=0"
assert_has "forces DPM=0"                     "$optline" "NVreg_DynamicPowerManagement=0( |$)"
assert_not "drops the distro's 0x02"          "$optline" "0x02"
assert_eq  "exactly one options line"         "$(grep -cE '^options nvidia' <<<"$out")" "1"
assert_eq  "exactly one DPM assignment"       "$(grep -oE 'NVreg_DynamicPowerManagement=' <<<"$optline" | wc -l)" "1"
write_modprobe_shadow "$T/etc/nvidia.conf" write
assert_rc  "write mode creates the file"      0 test -f "$T/etc/nvidia.conf"
assert_eq  "file name shadows the distro file by name" "$(basename "$T/etc/nvidia.conf")" "$(basename "$T/usrlib/nvidia.conf")"
rm -f "$T/usrlib/nvidia.conf"
out=$(write_modprobe_shadow "$T/etc/nvidia.conf")
assert_eq  "no distro file -> just DPM=0"     "$(grep -E '^options nvidia' <<<"$out")" "options nvidia NVreg_DynamicPowerManagement=0"

echo "== modprobe ordering (the trap itself) =="
# '-' (0x2D) sorts before '.' (0x2E): the old file name loses to nvidia.conf.
sorted=$(printf '%s\n' nvidia.conf nvidia-xgm-egpu.conf nvidia-sleep.conf | LC_ALL=C sort)
assert_eq "nvidia-xgm-egpu.conf sorts BEFORE nvidia.conf (so it lost)" "$(tail -1 <<<"$sorted")" "nvidia.conf"

echo "== autoprobe save/restore =="
echo 1 > "$T/drivers_autoprobe"
DRY_RUN=0
autoprobe_disable >/dev/null 2>&1
assert_eq "disable writes 0"                  "$(cat "$T/drivers_autoprobe")" "0"
autoprobe_restore >/dev/null 2>&1
assert_eq "restore puts back the saved 1"     "$(cat "$T/drivers_autoprobe")" "1"
autoprobe_restore >/dev/null 2>&1
assert_eq "second restore is a no-op"         "$(cat "$T/drivers_autoprobe")" "1"
DRY_RUN=1; echo 1 > "$T/drivers_autoprobe"
autoprobe_disable >/dev/null 2>&1
assert_eq "dry-run does not write"            "$(cat "$T/drivers_autoprobe")" "1"
DRY_RUN=0

echo "== nvidia_gpu_power_status =="
mkdir -p "$T/gpus/0000:01:00.0"
printf 'Runtime D3 status:          Enabled (fine-grained)\nVideo Memory:               Active\n' > "$T/gpus/0000:01:00.0/power"
assert_eq "parses Enabled"                    "$(nvidia_gpu_power_status 0000:01:00.0)" "Enabled (fine-grained)"
printf 'Runtime D3 status:          Not supported\n' > "$T/gpus/0000:01:00.0/power"
assert_eq "parses Not supported"              "$(nvidia_gpu_power_status 0000:01:00.0)" "Not supported"
assert_eq "empty for unknown GPU"             "$(nvidia_gpu_power_status 0000:09:00.0)" ""

echo "== watch output is locale-safe =="
out=$(LC_ALL=fr_FR.UTF-8 bash -c 'printf "%2d.%d\n" 3 5' 2>&1)
assert_eq "integer time formatting under fr_FR" "$out" " 3.5"
out=$(LC_ALL=fr_FR.UTF-8 bash -c 'printf "%5.1f\n" 3.5' 2>&1)
# the error text is localised (fr: "nombre non valable"), and a broken run
# prints a comma-decimal or nothing useful — match any of those.
assert_has "(control) float formatting DOES break under fr_FR" "$out" "invalid|valable|3,"

echo "== library mode =="
assert_rc "sourcing in library mode does not dispatch" 0 bash -c 'XGM_LIBRARY_MODE=1 source bin/xgm-egpu; declare -F cmd_on >/dev/null'
assert_rc "script still parses"               0 bash -n bin/xgm-egpu

echo
printf '%d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
