#!/usr/bin/env bash
# xgm-egpu test-suite. No root, no hardware, no network: every check runs the
# tool's functions in library mode against fixture files in a temp dir.
#
#   tests/run.sh
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
PASS=0; FAIL=0

pass() { PASS=$((PASS+1)); printf '  ok   %s\n' "$1"; }
fail() { FAIL=$((FAIL+1)); printf '  FAIL %s\n       %s\n' "$1" "$2"; }
assert_eq() { [[ "$2" == "$3" ]] && pass "$1" || fail "$1" "expected [$3] got [$2]"; }
assert_rc() { local label=$1 want=$2; shift 2; "$@" >/dev/null 2>&1; local rc=$?; [[ $rc -eq $want ]] && pass "$label" || fail "$label" "expected rc=$want got rc=$rc"; }
assert_has() { grep -qE -- "$3" <<<"$2" && pass "$1" || fail "$1" "missing /$3/ in: $2"; }
assert_not() { grep -qE -- "$3" <<<"$2" && fail "$1" "unexpected /$3/ in: $2" || pass "$1"; }
# for functions that may call die (which exits): run them in a subshell
sub() { ( "$@" ); }

# Load the tool with every path pointed into the fixture tree.
load() {
    export XGM_NV_PARAMS=$T/params XGM_NV_GPUS_DIR=$T/gpus \
           XGM_MKINITCPIO_CONF=$T/mkinitcpio.conf XGM_MKINITCPIO_D=$T/mkinitcpio.conf.d \
           XGM_DISTRO_MODPROBE=$T/usrlib/nvidia.conf XGM_ETC_MODPROBE_D=$T/etc \
           XGM_AUTOPROBE=$T/drivers_autoprobe XGM_STATE_DIR=$T/state \
           XGM_SYS_MODULE=$T/module XGM_SYSFS_PCI=$T/pci XGM_DRM_POLL=$T/drm_poll XGM_PSTORE=$T/pstore XGM_EFI_PSTORE_DISABLE=$T/efi_pstore_disable XGM_BUGREPORT_DIR=$T/bugreports
    mkdir -p "$T/gpus" "$T/mkinitcpio.conf.d" "$T/usrlib" "$T/etc" "$T/module" "$T/pci"
    # shellcheck disable=SC1091
    XGM_LIBRARY_MODE=1 source bin/xgm-egpu
}
load

echo "== nvidia_dpm_value =="
printf 'Foo: 1\nDynamicPowerManagement: 2\nDynamicPowerManagementVideoMemoryThreshold: 200\n' > "$T/params"
assert_eq "reads the module value"            "$(nvidia_dpm_value)" "2"
printf 'DynamicPowerManagement: 0\n' > "$T/params"
assert_eq "reads 0"                           "$(nvidia_dpm_value)" "0"
printf 'DynamicPowerManagementVideoMemoryThreshold: 200\n' > "$T/params"
assert_eq "does not match the Threshold key"  "$(nvidia_dpm_value)" ""
rm -f "$T/params"
assert_eq "empty when driver not loaded"      "$(nvidia_dpm_value)" ""

echo "== preflight_rtd3 =="
printf 'DynamicPowerManagement: 2\n' > "$T/params"
assert_rc "refuses when RTD3 armed (2)"       1 preflight_rtd3
printf 'DynamicPowerManagement: 3\n' > "$T/params"
assert_rc "refuses on driver default (3)"     1 preflight_rtd3
printf 'DynamicPowerManagement: 0\n' > "$T/params"
assert_rc "passes when disarmed (0)"          0 preflight_rtd3
rm -f "$T/params"
assert_rc "defers (passes) when not loaded"   0 preflight_rtd3
printf 'DynamicPowerManagement: 2\n' > "$T/params"
out=$(preflight_rtd3 2>&1)
assert_has "refusal explains the 10s timer"   "$out" "10s"
assert_has "refusal names the fix"            "$out" "install-rules"

echo "== initramfs_has_nvidia =="
printf 'MODULES=()\nHOOKS=(base)\n' > "$T/mkinitcpio.conf"
assert_rc "MODULES=() and no drop-in -> no"   1 initramfs_has_nvidia
printf 'MODULES=(nvidia nvidia_drm)\n' > "$T/mkinitcpio.conf"
assert_rc "MODULES=(nvidia) in main -> yes"   0 initramfs_has_nvidia
printf 'MODULES=()\n' > "$T/mkinitcpio.conf"
printf '# generated by chwd\nMODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)\n' > "$T/mkinitcpio.conf.d/10-chwd.conf"
assert_rc "MODULES+= in conf.d (CachyOS chwd) -> yes" 0 initramfs_has_nvidia
printf '# MODULES+=(nvidia)\n' > "$T/mkinitcpio.conf.d/10-chwd.conf"
assert_rc "commented-out drop-in -> no"       1 initramfs_has_nvidia
printf 'MODULES+=(amdgpu)\n' > "$T/mkinitcpio.conf.d/10-chwd.conf"
assert_rc "other module in drop-in -> no"     1 initramfs_has_nvidia
rm -f "$T/mkinitcpio.conf.d/10-chwd.conf"

echo "== write_modprobe_shadow =="
cat > "$T/usrlib/nvidia.conf" <<'D'
# distro file, CachyOS style, with a continuation line
options nvidia NVreg_InitializeSystemMemoryAllocations=0 \
    NVreg_DynamicPowerManagement=0x02
D
out=$(write_modprobe_shadow "$T/etc/nvidia.conf")
optline=$(grep -E '^options nvidia' <<<"$out")
assert_has "keeps the distro's other option"  "$optline" "NVreg_InitializeSystemMemoryAllocations=0"
assert_has "forces DPM=0"                     "$optline" "NVreg_DynamicPowerManagement=0( |$)"
assert_not "drops the distro's 0x02"          "$optline" "0x02"
assert_eq  "exactly one options line"         "$(grep -cE '^options nvidia' <<<"$out")" "1"
assert_eq  "exactly one DPM assignment"       "$(grep -oE 'NVreg_DynamicPowerManagement=' <<<"$optline" | wc -l)" "1"
write_modprobe_shadow "$T/etc/nvidia.conf" write
assert_rc  "write mode creates the file"      0 test -f "$T/etc/nvidia.conf"
assert_eq  "file name shadows the distro file by name" "$(basename "$T/etc/nvidia.conf")" "$(basename "$T/usrlib/nvidia.conf")"
rm -f "$T/usrlib/nvidia.conf"
out=$(write_modprobe_shadow "$T/etc/nvidia.conf")
assert_eq  "no distro file -> just DPM=0"     "$(grep -E '^options nvidia' <<<"$out")" "options nvidia NVreg_DynamicPowerManagement=0"

echo "== modprobe ordering (the trap itself) =="
# '-' (0x2D) sorts before '.' (0x2E): the old file name loses to nvidia.conf.
sorted=$(printf '%s\n' nvidia.conf nvidia-xgm-egpu.conf nvidia-sleep.conf | LC_ALL=C sort)
assert_eq "nvidia-xgm-egpu.conf sorts BEFORE nvidia.conf (so it lost)" "$(tail -1 <<<"$sorted")" "nvidia.conf"

echo "== autoprobe save/restore =="
echo 1 > "$T/drivers_autoprobe"
DRY_RUN=0
autoprobe_disable >/dev/null 2>&1
assert_eq "disable writes 0"                  "$(cat "$T/drivers_autoprobe")" "0"
autoprobe_restore >/dev/null 2>&1
assert_eq "restore puts back the saved 1"     "$(cat "$T/drivers_autoprobe")" "1"
autoprobe_restore >/dev/null 2>&1
assert_eq "second restore is a no-op"         "$(cat "$T/drivers_autoprobe")" "1"
DRY_RUN=1; echo 1 > "$T/drivers_autoprobe"
autoprobe_disable >/dev/null 2>&1
assert_eq "dry-run does not write"            "$(cat "$T/drivers_autoprobe")" "1"
DRY_RUN=0

echo "== nvidia_gpu_power_status =="
mkdir -p "$T/gpus/0000:01:00.0"
printf 'Runtime D3 status:          Enabled (fine-grained)\nVideo Memory:               Active\n' > "$T/gpus/0000:01:00.0/power"
assert_eq "parses Enabled"                    "$(nvidia_gpu_power_status 0000:01:00.0)" "Enabled (fine-grained)"
printf 'Runtime D3 status:          Not supported\n' > "$T/gpus/0000:01:00.0/power"
assert_eq "parses Not supported"              "$(nvidia_gpu_power_status 0000:01:00.0)" "Not supported"
assert_eq "empty for unknown GPU"             "$(nvidia_gpu_power_status 0000:09:00.0)" ""

echo "== watch output is locale-safe =="
out=$(LC_ALL=fr_FR.UTF-8 bash -c 'printf "%2d.%d\n" 3 5' 2>&1)
assert_eq "integer time formatting under fr_FR" "$out" " 3.5"
out=$(LC_ALL=fr_FR.UTF-8 bash -c 'printf "%5.1f\n" 3.5' 2>&1)
# the error text is localised (fr: "nombre non valable"), and a broken run
# prints a comma-decimal or nothing useful — match any of those.
assert_has "(control) float formatting DOES break under fr_FR" "$out" "invalid|valable|3,"

echo "== nvidia_extra_refs (refcnt arithmetic) =="
mkdir -p "$T/module/nvidia/holders"
echo 3 > "$T/module/nvidia/refcnt"
touch "$T/module/nvidia/holders/nvidia_uvm" "$T/module/nvidia/holders/nvidia_drm" "$T/module/nvidia/holders/nvidia_modeset"
assert_eq "refcnt 3 with 3 holders -> 0 extra (safe)"    "$(nvidia_extra_refs)" "0"
echo 19 > "$T/module/nvidia/refcnt"
assert_eq "refcnt 19 with 3 holders -> 16 extra (fds open)" "$(nvidia_extra_refs)" "16"
rm -rf "$T/module/nvidia"
assert_eq "module absent -> 0"                            "$(nvidia_extra_refs)" "0"
assert_rc "module absent -> rc 1"                         1 nvidia_extra_refs

echo "== device_alive (zombie detection) =="
mkdir -p "$T/pci/0000:01:00.0"
echo "8.0 GT/s PCIe" > "$T/pci/0000:01:00.0/current_link_speed"
assert_rc "present + answering -> alive"                  0 device_alive 0000:01:00.0
: > "$T/pci/0000:01:00.0/current_link_speed"
assert_rc "present but config reads empty -> dead (zombie)" 1 device_alive 0000:01:00.0
rm -rf "$T/pci/0000:01:00.0"
assert_rc "directory gone -> dead"                        1 device_alive 0000:01:00.0

echo "== reload-driver refuses when unsafe (dry-run, no root needed for the guard) =="
mkdir -p "$T/module/nvidia/holders"; echo 5 > "$T/module/nvidia/refcnt"
touch "$T/module/nvidia/holders/a" "$T/module/nvidia/holders/b" "$T/module/nvidia/holders/c"
# stub the root/interface/attr checks so only the refcount guard is exercised
need_root() { :; }; check_interface() { :; }; read_attr() { echo 0; }; nv_holders() { echo "4242 fakeproc"; }
out=$(DRY_RUN=1 sub cmd_reload_driver 2>&1); rc=$?
assert_eq  "refuses with extra refs (rc 1)"               "$rc" "1"
assert_has "names the holder"                             "$out" "4242 fakeproc"
echo 3 > "$T/module/nvidia/refcnt"; nv_holders() { :; }
out=$(DRY_RUN=1 sub cmd_reload_driver 2>&1); rc=$?
assert_eq  "proceeds (dry-run) when refs == holders"      "$rc" "0"
assert_has "dry-run says what it would unload"            "$out" "would unload nvidia_drm nvidia_modeset nvidia_uvm nvidia"
read_attr() { echo 1; }
out=$(DRY_RUN=1 sub cmd_reload_driver 2>&1); rc=$?
assert_eq  "refuses while egpu_enable=1"                  "$rc" "1"
assert_has "explains eGPU must be off"                    "$out" "eGPU OFF"

echo "== drm poll save/restore =="
echo Y > "$T/drm_poll"
DRY_RUN=0
drm_poll_disable >/dev/null 2>&1
assert_eq "disable writes 0"                  "$(cat "$T/drm_poll")" "0"
drm_poll_restore >/dev/null 2>&1
assert_eq "restore puts back the saved Y"     "$(cat "$T/drm_poll")" "Y"
drm_poll_restore >/dev/null 2>&1
assert_eq "second restore is a no-op"         "$(cat "$T/drm_poll")" "Y"
DRY_RUN=1; echo Y > "$T/drm_poll"
drm_poll_disable >/dev/null 2>&1
assert_eq "dry-run does not write"            "$(cat "$T/drm_poll")" "Y"
DRY_RUN=0
rm -f "$T/drm_poll"
assert_rc "missing knob -> rc 1, no crash"    1 drm_poll_disable

echo "== pciehp Slot Control mask arithmetic =="
# bit3 PDCE=0x8, bit5 HPIE=0x20, bit12 DLLSCE=0x1000 -> mask 0x1028
assert_eq "mask constant is 0x1028"           "$(printf '0x%x' "$PCIEHP_MASK_BITS")" "0x1028"
assert_eq "clears HPIE/DLLSCE/PDCE, keeps the rest" "$(printf '%04x' $(( 0x1fff & ~PCIEHP_MASK_BITS )))" "0fd7"
assert_eq "already-clear value is unchanged"  "$(printf '%04x' $(( 0x0fd7 & ~PCIEHP_MASK_BITS )))" "0fd7"
assert_eq "typical live value 0x10?? loses only bit12" "$(printf '%04x' $(( 0x1038 & ~PCIEHP_MASK_BITS )))" "0010"
echo "--- mask/restore refuse cleanly without setpci / root port ---"
ROOT_PORT=""; DRY_RUN=1
assert_rc "pciehp_mask dies without a root port"  1 sub pciehp_mask
ROOT_PORT=0000:00:01.1
_SLOTCTL_SAVED=""
assert_rc "pciehp_restore with nothing saved is a no-op (rc 0)" 0 pciehp_restore
DRY_RUN=0

echo "== smi_line =="
assert_eq "no nvidia-smi on PATH -> empty, rc 0" "$(PATH=/nonexistent smi_line; echo "rc=$?")" "rc=0"

echo "== cap_gpu_power =="
out=$(PATH=/nonexistent DRY_RUN=0 sub cap_gpu_power 0000:01:00.0 2>&1); rc=$?
assert_eq  "no nvidia-smi -> rc 1"                "$rc" "1"
assert_has "no nvidia-smi -> says so"             "$out" "nvidia-smi absent"
mkdir -p "$T/fakebin"; printf '#!/bin/sh\nexit 0\n' > "$T/fakebin/nvidia-smi"; chmod +x "$T/fakebin/nvidia-smi"
out=$(PATH="$T/fakebin:$PATH" DRY_RUN=1 sub cap_gpu_power 0000:01:00.0 2>&1); rc=$?
assert_eq  "dry-run -> rc 0"                      "$rc" "0"
assert_has "dry-run announces the clamp plan"     "$out" "would: nvidia-smi -pm 1; -lgc 0,405"

echo "== option-in-command-slot gives a real message, not the usage dump =="
out=$(bash bin/xgm-egpu --cap-power --force-kill 2>&1); rc=$?
assert_eq  "rc 1"                                 "$rc" "1"
assert_has "names the mistake"                    "$out" "is an option, not a command"
assert_has "shows the corrected command"          "$out" "on --cap-power --force-kill"
assert_not "does NOT dump the full usage"         "$out" "Options:"

echo "== capture =="
assert_eq  "sysctl list is well-formed key=value"  "$(printf '%s\n' "${CAPTURE_SYSCTLS[@]}" | grep -cvE '^[a-z_.]+=[0-9]+$')" "0"
assert_has "arms the hard-lockup detector"         "${CAPTURE_SYSCTLS[*]}" "kernel.nmi_watchdog=1"
assert_has "hung_task -> panic (the D-state case)" "${CAPTURE_SYSCTLS[*]}" "kernel.hung_task_panic=1"
need_root() { :; }
out=$(DRY_RUN=1 sub cmd_capture arm 2>&1); rc=$?
assert_eq  "dry-run arm rc 0"                      "$rc" "0"
assert_has "dry-run lists the sysctls"             "$out" "would set kernel.nmi_watchdog=1"
assert_has "dry-run mentions pstore mount"         "$out" "would mount pstore"
assert_has "hung_task timeout lowered from 120"     "${CAPTURE_SYSCTLS[*]}" "kernel.hung_task_timeout_secs=30"
echo 1 > "$T/efi_pstore_disable"
out=$(DRY_RUN=1 sub cmd_capture arm 2>&1)
assert_has "dry-run would clear efi_pstore.pstore_disable" "$out" "would write 0 > $T/efi_pstore_disable"
rm -f "$T/efi_pstore_disable"
out=$(DRY_RUN=1 sub cmd_capture arm 2>&1)
assert_has "missing knob -> warns with the cmdline fallback" "$out" "efi_pstore.pstore_disable=0"
# the kernel reports a NULL pstore backend as the literal string "(null)"
be='(null)'; [[ $be == "(null)" ]] && be=""
assert_eq  "'(null)' backend string is treated as no backend" "$be" ""
rm -rf "$T/pstore"
out=$(sub cmd_capture read 2>&1); rc=$?
assert_eq  "read with no pstore dir -> rc 1"       "$rc" "1"
mkdir -p "$T/pstore"
out=$(sub cmd_capture read 2>&1); rc=$?
assert_eq  "read with empty pstore -> rc 1"        "$rc" "1"
assert_has "read explains no records"              "$out" "no records"
printf 'Panic#1 Part1\n[  123.4] BUG: kernel NULL\n' > "$T/pstore/dmesg-efi-1"
out=$(sub cmd_capture read 2>&1); rc=$?
assert_eq  "read with a record -> rc 0"            "$rc" "0"
assert_has "read prints the record"                "$out" "kernel NULL"
out=$(sub cmd_capture bogus 2>&1); rc=$?
assert_eq  "unknown subcommand -> rc 1"            "$rc" "1"

echo "== collect_gpu_crash_dump =="
mkdir -p "$T/bugreports"
out=$(PATH=/nonexistent DRY_RUN=0 sub collect_gpu_crash_dump 2>&1); rc=$?
assert_eq  "no nvidia-bug-report.sh -> rc 1"            "$rc" "1"
assert_has "says the tool is missing"                   "$out" "not installed"
mkdir -p "$T/fakebin"
printf '#!/bin/sh\nexit 0\n' > "$T/fakebin/nvidia-bug-report.sh"; chmod +x "$T/fakebin/nvidia-bug-report.sh"
out=$(PATH="$T/fakebin:$PATH" DRY_RUN=1 sub collect_gpu_crash_dump 2>&1); rc=$?
assert_eq  "dry-run -> rc 0"                            "$rc" "0"
assert_has "dry-run shows the output path in BUGREPORT_DIR" "$out" "$T/bugreports/xgm-bugreport-"
# a fake reporter that honours --output-file and writes a non-empty gz
cat > "$T/fakebin/nvidia-bug-report.sh" <<'FAKE'
#!/bin/sh
while [ $# -gt 0 ]; do case "$1" in --output-file) shift; printf 'fake' | gzip > "$1";; esac; shift; done
FAKE
chmod +x "$T/fakebin/nvidia-bug-report.sh"
out=$(PATH="$T/fakebin:$PATH" DRY_RUN=0 sub collect_gpu_crash_dump 2>&1); rc=$?
assert_eq  "real run with a working reporter -> rc 0"   "$rc" "0"
assert_has "reports the saved path"                     "$out" "crash dump saved"
assert_eq  "a non-empty dump file exists"               "$(ls "$T/bugreports"/xgm-bugreport-*.log.gz 2>/dev/null | wc -l)" "1"
# a reporter that produces nothing
printf '#!/bin/sh\nexit 0\n' > "$T/fakebin/nvidia-bug-report.sh"
rm -f "$T/bugreports"/*
out=$(PATH="$T/fakebin:$PATH" DRY_RUN=0 sub collect_gpu_crash_dump 2>&1); rc=$?
assert_eq  "reporter that writes nothing -> rc 1"       "$rc" "1"
assert_has "says it produced nothing"                   "$out" "produced nothing"

echo "== library mode =="
assert_rc "sourcing in library mode does not dispatch" 0 bash -c 'XGM_LIBRARY_MODE=1 source bin/xgm-egpu; declare -F cmd_on >/dev/null'
assert_rc "script still parses"               0 bash -n bin/xgm-egpu

echo
printf '%d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
